name: CI/CD Starter for GreetingService

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and test with Maven
      run: mvn clean install
      working-directory: greeting-service

    - name: Upload JAR and BAT as artifact
      uses: actions/upload-artifact@v4
      with:
       name: greeting-service-artifacts
       path: |
          greeting-service/target/greeting-service.jar
          greeting-service/scripts/GreetingApp.bat


